locals {
  prefix = "${var.app_name}-${var.environment}"
}

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

# ─── Bedrock Guardrail ────────────────────────────────────────────────────────
resource "aws_bedrock_guardrail" "main" {
  name                      = "${local.prefix}-StudentSupportGuardrail"
  description               = "Protect AI responses for university students."
  blocked_input_messaging   = "Sorry, the model cannot answer this question."
  blocked_outputs_messaging = "Sorry, the model cannot answer this question."

  content_policy_config {
    filters_config {
      type            = "VIOLENCE"
      input_strength  = "HIGH"
      output_strength = "HIGH"
    }
    filters_config {
      type            = "HATE"
      input_strength  = "HIGH"
      output_strength = "HIGH"
    }
    filters_config {
      type            = "SEXUAL"
      input_strength  = "HIGH"
      output_strength = "HIGH"
    }
    filters_config {
      type            = "INSULTS"
      input_strength  = "HIGH"
      output_strength = "HIGH"
    }
    filters_config {
      type            = "MISCONDUCT"
      input_strength  = "HIGH"
      output_strength = "HIGH"
    }
    filters_config {
      type            = "PROMPT_ATTACK"
      input_strength  = "NONE"
      output_strength = "NONE"
    }
  }

  word_policy_config {
    words_config { text = "hack exam" }
    words_config { text = "cheat exam" }
    words_config { text = "generate malware" }
    managed_word_lists_config { type = "PROFANITY" }
  }

  sensitive_information_policy_config {
    pii_entities_config {
      type   = "EMAIL"
      action = "ANONYMIZE"
    }
    pii_entities_config {
      type   = "PASSWORD"
      action = "ANONYMIZE"
    }
    pii_entities_config {
      type   = "CREDIT_DEBIT_CARD_CVV"
      action = "ANONYMIZE"
    }
    pii_entities_config {
      type   = "CREDIT_DEBIT_CARD_EXPIRY"
      action = "ANONYMIZE"
    }
    pii_entities_config {
      type   = "SWIFT_CODE"
      action = "ANONYMIZE"
    }
    pii_entities_config {
      type   = "AWS_SECRET_KEY"
      action = "ANONYMIZE"
    }
    pii_entities_config {
      type   = "AWS_ACCESS_KEY"
      action = "ANONYMIZE"
    }
  }

  tags = { Name = "${local.prefix}-StudentSupportGuardrail" }
}

resource "aws_bedrock_guardrail_version" "v1" {
  guardrail_arn = aws_bedrock_guardrail.main.guardrail_arn
  description   = "Initial published version"
}

# ─── S3 Bucket — document storage for Knowledge Base ─────────────────────────
# Admins upload PDFs here via pre-signed PUT URLs generated by the
# admin-upload-document Lambda. Bedrock ingests from this bucket.
resource "aws_s3_bucket" "knowledge_docs" {
  bucket = "${local.prefix}-knowledge-docs-${data.aws_caller_identity.current.account_id}"

  tags = {
    Name    = "${local.prefix}-knowledge-docs"
    Purpose = "Bedrock Knowledge Base document source"
  }
}

resource "aws_s3_bucket_versioning" "knowledge_docs" {
  bucket = aws_s3_bucket.knowledge_docs.id
  versioning_configuration { status = "Enabled" }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "knowledge_docs" {
  bucket = aws_s3_bucket.knowledge_docs.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "knowledge_docs" {
  bucket                  = aws_s3_bucket.knowledge_docs.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# ─── IAM Role — Bedrock Knowledge Base service role ──────────────────────────
# Bedrock assumes this role to:
#   1. Read source documents from the S3 docs bucket
#   2. Call Titan Embeddings V2 to embed each chunk
#   3. Write embeddings to S3 Vectors (external, not managed by Terraform)
resource "aws_iam_role" "bedrock_kb" {
  name = "${local.prefix}-bedrock-kb-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "bedrock.amazonaws.com" }
      Action    = "sts:AssumeRole"
      Condition = {
        StringEquals = {
          "aws:SourceAccount" = data.aws_caller_identity.current.account_id
        }
        ArnLike = {
          "aws:SourceArn" = "arn:aws:bedrock:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:knowledge-base/*"
        }
      }
    }]
  })
}

resource "aws_iam_role_policy" "bedrock_kb_s3" {
  name = "${local.prefix}-bedrock-kb-s3-policy"
  role = aws_iam_role.bedrock_kb.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = ["s3:GetObject", "s3:ListBucket"]
        Resource = [
          aws_s3_bucket.knowledge_docs.arn,
          "${aws_s3_bucket.knowledge_docs.arn}/*",
        ]
      },
      {
        Effect   = "Allow"
        Action   = ["bedrock:InvokeModel"]
        Resource = "arn:aws:bedrock:${data.aws_region.current.name}::foundation-model/amazon.titan-embed-text-v2:0"
      },
    ]
  })
}

# S3 Vectors permissions — only attached when a vector index ARN is known.
resource "aws_iam_role_policy" "bedrock_kb_s3vectors" {
  count = var.s3_vectors_index_arn != "" ? 1 : 0
  name  = "${local.prefix}-bedrock-kb-s3vectors-policy"
  role  = aws_iam_role.bedrock_kb.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "s3vectors:PutVectors",
          "s3vectors:GetVectors",
          "s3vectors:DeleteVectors",
          "s3vectors:QueryVectors",
          "s3vectors:ListVectors",
          "s3vectors:DescribeIndex",
        ]
        Resource = [
          var.s3_vectors_index_arn,
          "${var.s3_vectors_index_arn}/*",
        ]
      },
    ]
  })
}

# ─── NOTE: Bedrock Knowledge Base + Data Source ───────────────────────────────
# The aws_bedrockagent_knowledge_base resource with S3_VECTORS storage type
# is NOT yet supported by the Terraform AWS provider (as of v6.x, 2025).
#
# After running this Terraform apply, create the Knowledge Base manually:
#
#   BUCKET=$(terraform output -raw knowledge_docs_bucket)
#   KB_ROLE=$(terraform output -raw knowledge_base_role_arn)
#
#   # 1. Create S3 Vectors bucket
#   aws s3vectors create-vector-bucket \
#     --vector-bucket-name aisss-dev-knowledge-vectors \
#     --region us-east-1
#
#   # 2. Create vector index (1024 dims = Titan Embed V2)
#   aws s3vectors create-index \
#     --vector-bucket-name aisss-dev-knowledge-vectors \
#     --index-name knowledge-index \
#     --data-type float32 \
#     --dimension 1024 \
#     --distance-metric cosine \
#     --region us-east-1
#
#   # 3. Create Knowledge Base
#   aws bedrock-agent create-knowledge-base \
#     --name "aisss-dev-knowledge-base" \
#     --role-arn "$KB_ROLE" \
#     --knowledge-base-configuration '{"type":"VECTOR","vectorKnowledgeBaseConfiguration":{"embeddingModelArn":"arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v2:0","embeddingModelConfiguration":{"bedrockEmbeddingModelConfiguration":{"dimensions":1024}}}}' \
#     --storage-configuration '{"type":"S3_VECTORS","s3VectorsConfiguration":{"indexArn":"<S3_VECTORS_INDEX_ARN>"}}' \
#     --region us-east-1
#
#   # 4. Create Data Source
#   KB_ID=<output from step 3>
#   aws bedrock-agent create-data-source \
#     --knowledge-base-id "$KB_ID" \
#     --name "aisss-dev-s3-docs" \
#     --data-source-configuration "{\"type\":\"S3\",\"s3Configuration\":{\"bucketArn\":\"arn:aws:s3:::$BUCKET\"}}" \
#     --vector-ingestion-configuration '{"chunkingConfiguration":{"chunkingStrategy":"FIXED_SIZE","fixedSizeChunkingConfiguration":{"maxTokens":512,"overlapPercentage":20}}}' \
#     --region us-east-1
#
#   # 5. Add these to GitHub Secrets or terraform.tfvars:
#   #    TF_VAR_bedrock_knowledge_base_id = <KB_ID>
#   #    TF_VAR_bedrock_knowledge_data_source_id = <DATA_SOURCE_ID>
#   #    TF_VAR_knowledge_docs_bucket = <BUCKET>

# ─── OpenSearch Serverless — Vector Store for Bedrock KB ─────────────────────
# Migrated from S3 Vectors (had 2048-byte filterable metadata limit that caused
# all ingestion jobs to fail). OpenSearch Serverless has no such constraint.
#
# Collection:  aisss-dev-kb  (id: g7i64ouqqxc3h6a7fsm9)
# Vector index: bedrock-knowledge-base-default-index  (1024-dim, HNSW, faiss)
# KB ID:       86HYJUEMJL  (passed in via var.bedrock_knowledge_base_id)
# DS ID:       OTSDN45AJ7  (passed in via var.bedrock_knowledge_data_source_id)

resource "aws_opensearchserverless_security_policy" "kb_enc" {
  name        = "${local.prefix}-kb-enc"
  type        = "encryption"
  description = "Encryption policy for Bedrock KB vector collection"
  policy = jsonencode({
    Rules = [{
      ResourceType = "collection"
      Resource     = ["collection/${local.prefix}-kb"]
    }]
    AWSOwnedKey = true
  })
}

resource "aws_opensearchserverless_security_policy" "kb_net" {
  name        = "${local.prefix}-kb-net"
  type        = "network"
  description = "Network policy — public access for Bedrock KB collection"
  policy = jsonencode([{
    Rules = [
      { ResourceType = "collection", Resource = ["collection/${local.prefix}-kb"] },
      { ResourceType = "dashboard", Resource = ["collection/${local.prefix}-kb"] },
    ]
    AllowFromPublic = true
  }])
}

resource "aws_opensearchserverless_collection" "kb" {
  name        = "${local.prefix}-kb"
  type        = "VECTORSEARCH"
  description = "Bedrock Knowledge Base vector store for AISSS"

  depends_on = [
    aws_opensearchserverless_security_policy.kb_enc,
    aws_opensearchserverless_security_policy.kb_net,
  ]
}

resource "aws_opensearchserverless_access_policy" "kb_access" {
  name        = "${local.prefix}-kb-access"
  type        = "data"
  description = "Data access — Bedrock KB role and Lambda execution role"
  policy = jsonencode([{
    Rules = [
      {
        ResourceType = "collection"
        Resource     = ["collection/${local.prefix}-kb"]
        Permission = [
          "aoss:CreateCollectionItems",
          "aoss:DeleteCollectionItems",
          "aoss:UpdateCollectionItems",
          "aoss:DescribeCollectionItems",
        ]
      },
      {
        ResourceType = "index"
        Resource     = ["index/${local.prefix}-kb/*"]
        Permission = [
          "aoss:CreateIndex",
          "aoss:DeleteIndex",
          "aoss:UpdateIndex",
          "aoss:DescribeIndex",
          "aoss:ReadDocument",
          "aoss:WriteDocument",
        ]
      },
    ]
    Principal = [
      aws_iam_role.bedrock_kb.arn,
      var.lambda_execution_role_arn,
    ]
    Description = "Bedrock KB and Lambda access"
  }])
}
