/**
 * build-amplify.mjs
 *
 * Packages the Qwik City SSR app for AWS Amplify Hosting WEB_COMPUTE.
 *
 * Amplify deployment spec:
 *   https://docs.aws.amazon.com/amplify/latest/userguide/ssr-deployment-specification.html
 *
 * Build inputs:
 *   dist/          — client assets from `vite build` (qwikVite puts them here)
 *   dist/server/   — SSR render bundle from `vite build --mode ssr`
 *
 * Output:
 *   .amplify-hosting/
 *   ├── static/                    ← CDN-served client assets
 *   ├── compute/default/
 *   │   ├── entry.ssr.js           ← Qwik render bundle
 *   │   ├── server.js              ← Node HTTP server (entry point for Amplify)
 *   │   └── node_modules/          ← runtime deps copied from project
 *   └── deploy-manifest.json
 */

import {
  cpSync, mkdirSync, rmSync, existsSync,
  writeFileSync, readFileSync,
} from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root      = resolve(__dirname, "..");
// In an npm workspace, packages are hoisted to the repo root, not frontend/node_modules/
const nodeModules = existsSync(resolve(root, "node_modules/@builder.io/qwik-city"))
  ? resolve(root, "node_modules")           // local install (non-workspace)
  : resolve(root, "../node_modules");       // workspace root (hoisted)

// ─── Paths ────────────────────────────────────────────────────────────────────
const distClient  = resolve(root, "dist");
const distServer  = resolve(root, "dist/server");
const amplifyOut  = resolve(root, ".amplify-hosting");
const staticOut   = resolve(amplifyOut, "static");
const computeOut  = resolve(amplifyOut, "compute/default");

// ─── Validate inputs ──────────────────────────────────────────────────────────
if (!existsSync(distClient)) {
  console.error("ERROR: dist/ not found — run 'npm run build.client' first.");
  process.exit(1);
}
if (!existsSync(distServer)) {
  console.error("ERROR: dist/server not found — run 'npm run build.server' first.");
  process.exit(1);
}

// ─── Clean previous output ───────────────────────────────────────────────────
if (existsSync(amplifyOut)) {
  rmSync(amplifyOut, { recursive: true, force: true });
  console.log("Cleaned previous .amplify-hosting/");
}

// ─── Static assets ───────────────────────────────────────────────────────────
// Copy dist/ (client assets) to static/, excluding dist/server/
mkdirSync(staticOut, { recursive: true });
cpSync(distClient, staticOut, {
  recursive: true,
  filter: (src) => !src.startsWith(distServer),
});
console.log("Copied client assets → .amplify-hosting/static/");

// ─── SSR bundle ──────────────────────────────────────────────────────────────
// Copy dist/server/ (Qwik render bundle) to compute/default/
mkdirSync(computeOut, { recursive: true });
cpSync(distServer, computeOut, { recursive: true });
console.log("Copied dist/server/ → .amplify-hosting/compute/default/");

const ssrBundle = "entry.ssr.js";
if (!existsSync(resolve(computeOut, ssrBundle))) {
  console.error(`ERROR: '${ssrBundle}' not found in dist/server/`);
  process.exit(1);
}

// ─── Runtime node_modules ─────────────────────────────────────────────────────
// Amplify's compute sandbox is self-contained — no host node_modules.
// We copy only the packages needed at runtime (the Node middleware).
// @builder.io/qwik-city/middleware/node is the only direct runtime dep.
// It in turn depends on @builder.io/qwik (already bundled into entry.ssr.js)
// but its package.json still contains module resolution paths we need.
//
// We copy the minimum required packages:
const runtimePkgs = [
  "@builder.io/qwik-city",  // Node.js middleware (createQwikCity)
  "@builder.io/qwik",       // Qwik server runtime (renderToStream etc.)
];

const computeNodeModules = resolve(computeOut, "node_modules");
mkdirSync(computeNodeModules, { recursive: true });

for (const pkg of runtimePkgs) {
  const src  = resolve(nodeModules, pkg);
  const dest = resolve(computeNodeModules, pkg);
  if (!existsSync(src)) {
    console.error(`ERROR: node_modules/${pkg} not found — run 'npm ci' first.`);
    process.exit(1);
  }
  // Create scoped directory if needed (e.g. @builder.io)
  mkdirSync(resolve(computeNodeModules, pkg.split("/")[0]), { recursive: true });
  cpSync(src, dest, { recursive: true });
  console.log(`Copied node_modules/${pkg} → compute/default/node_modules/`);
}

// ─── server.js — Amplify compute entry point ─────────────────────────────────
// Amplify starts this with: node server.js
// It imports the Qwik City Node middleware and the SSR render bundle,
// then starts an HTTP server on port 3000.
//
// Note: @qwik-city-plan is a Vite virtual module that was bundled into
// entry.ssr.js at build time — we don't import it here.
//
const serverJs = `
// Auto-generated by scripts/build-amplify.mjs — do not edit
import { createQwikCity } from "@builder.io/qwik-city/middleware/node";
import render from "./entry.ssr.js";
import { createServer } from "node:http";

const { router, notFound } = createQwikCity({ render });
const port = parseInt(process.env.PORT ?? "3000", 10);

createServer(async (req, res) => {
  await router(req, res, () => {
    notFound(req, res, () => {});
  });
}).listen(port, () => {
  console.log("[aisss] Qwik City SSR server on http://localhost:" + port);
});
`.trimStart();

writeFileSync(resolve(computeOut, "server.js"), serverJs, "utf8");
console.log("Written .amplify-hosting/compute/default/server.js");

// ─── package.json for compute dir (needed for ESM resolution) ────────────────
// Node needs a package.json with "type":"module" to load .js files as ESM.
writeFileSync(
  resolve(computeOut, "package.json"),
  JSON.stringify({ type: "module", name: "aisss-compute" }, null, 2),
  "utf8"
);
console.log("Written .amplify-hosting/compute/default/package.json");

// ─── deploy-manifest.json ─────────────────────────────────────────────────────
let qwikVersion = "1.20.0";
try {
  const qwikPkg = JSON.parse(
    readFileSync(resolve(nodeModules, "@builder.io/qwik/package.json"), "utf8")
  );
  qwikVersion = qwikPkg.version ?? qwikVersion;
} catch { /* fallback */ }

const manifest = {
  version: 1,
  routes: [
    // Qwik's hashed JS chunks — immutable, very long cache
    {
      path: "/build/*",
      target: { kind: "Static", cacheControl: "public, max-age=31536000, immutable" },
    },
    // Public folder assets
    {
      path: "/assets/*",
      target: { kind: "Static", cacheControl: "public, max-age=86400" },
    },
    // Files with extensions → static first, SSR fallback on 404
    {
      path: "/*.*",
      target: { kind: "Static" },
      fallback: { kind: "Compute", src: "default" },
    },
    // Everything else → SSR server
    {
      path: "/*",
      target: { kind: "Compute", src: "default" },
    },
  ],
  computeResources: [{
    name: "default",
    runtime: "nodejs22.x",
    entrypoint: "server.js",
  }],
  framework: { name: "qwik-city", version: qwikVersion },
};

writeFileSync(
  resolve(amplifyOut, "deploy-manifest.json"),
  JSON.stringify(manifest, null, 2),
  "utf8"
);
console.log("Written .amplify-hosting/deploy-manifest.json");

// ─── Summary ──────────────────────────────────────────────────────────────────
console.log("\n✅ Amplify WEB_COMPUTE package ready:");
console.log("   Static     : .amplify-hosting/static/");
console.log("   Compute    : .amplify-hosting/compute/default/server.js");
console.log("   Manifest   : .amplify-hosting/deploy-manifest.json");
